#!/usr/bin/python

import os, sys
import utils

def get_author_info():
    config = utils.DockerConfig()

    name = config.get_author_name()
    email = config.get_author_email()

    if name and email:
        return '%s <%s>' % (name, email)

    return ''

def run_commit(container, msg, author_info):
    cmd = 'docker commit '

    if msg:
        cmd += "-m '%s' " % msg

    if author_info:
        cmd += "-a '%s' " % author_info

    cmd += '%s %s' % (container['id'], container['image'])

    print cmd
    os.system(cmd)

def prompt_message():
    return raw_input('Commit message: ')

if __name__ == '__main__':
    if not utils.check_permission():
        print 'Please run it with root permission'
        sys.exit(1)

    containers = utils.get_containers()
    author_info = get_author_info()

    c = utils.prompt_container(containers)
    m = prompt_message()
    run_commit(c, m, author_info)
