#!/usr/bin/python

import os, sys
import utils

def run_start(container):
    cmd = 'docker start -a -i %s' % container['id']

    print cmd
    os.system(cmd)

if __name__ == '__main__':
    if not utils.check_permission():
        print 'Please run it with root permission'
        sys.exit(1)

    containers = utils.get_containers()

    c = utils.prompt_container(containers)
    run_start(c)
